#!/bin/bash

CODE_SERVER_VERSION=2.1478-vsc1.38.1

# Enable the proxy extension in notebook and lab
jupyter serverextension enable --py jupyter_server_proxy
jupyter labextension install jupyterlab-server-proxy
jupyter lab build

# Download and install VS Code server
wget -q -O code-server.tar.gz https://github.com/cdr/code-server/releases/download/$CODE_SERVER_VERSION/code-server$CODE_SERVER_VERSION-linux-x64.tar.gz
tar xzf code-server.tar.gz
mkdir -p ~/.local/bin
mv code-server$CODE_SERVER_VERSION-linux-x64/code-server ~/.local/bin/
rm -rf code-server$CODE_SERVER_VERSION-linux-x64 code-server.tar.gz

# Install the VS code proxy
pip install -e.
